#' Sets off the workflow for the selected optimizer 
#' 
#' @noRd
.gl_run_fit_optimizer <- function(
    method,
    optimizer_context,
    mm,
    margin_dist,
    copula_link,
    copula_dist,
    dataset,
    include_dlcopdpar,
    check_dlcopdpar_gradient,
    discrete_score_method,
    cg_gradient_method,
    cg_hessian_method,
    verbose,
    cg_max_delta,
    max_outer_iter,
    check_elapsed_budget,
    cg_update_lambda,
    cg_max_lambda_updates,
    cg_lambda_update_every,
    lambda_penalty_K,
    cg_armijo_c1,
    cg_line_search,
    cg_max_line_search_evals,
    use_backtracking,
    backtracking_max_halves,
    cg_zeta_hessian,
    cg_max_stall,
    cg_raw_loglik_drop_tol,
    rs_smooth_trust_radius,
    rs_update_lambda,
    plot_results,
    true_val,
    max_inner_iter,
    max_negative_outer_streak,
    step_adjustment,
    max_steps,
    start_step_size,
    cg_runner_fn = .gl_run_cg_optimizer,
    rs_runner_fn = .gl_run_rs_optimizer) {
  if (identical(method, "CG")) {
    return(.gl_run_fit_cg_optimizer(
      optimizer_context = optimizer_context,
      mm = mm,
      margin_dist = margin_dist,
      copula_link = copula_link,
      copula_dist = copula_dist,
      dataset = dataset,
      include_dlcopdpar = include_dlcopdpar,
      cg_gradient_method = cg_gradient_method,
      cg_hessian_method = cg_hessian_method,
      verbose = verbose,
      cg_max_delta = cg_max_delta,
      max_outer_iter = max_outer_iter,
      check_elapsed_budget = check_elapsed_budget,
      cg_update_lambda = cg_update_lambda,
      cg_max_lambda_updates = cg_max_lambda_updates,
      cg_lambda_update_every = cg_lambda_update_every,
      lambda_penalty_K = lambda_penalty_K,
      cg_armijo_c1 = cg_armijo_c1,
      cg_line_search = cg_line_search,
      cg_max_line_search_evals = cg_max_line_search_evals,
      use_backtracking = use_backtracking,
      backtracking_max_halves = backtracking_max_halves,
      cg_zeta_hessian = cg_zeta_hessian,
      cg_max_stall = cg_max_stall,
      cg_raw_loglik_drop_tol = cg_raw_loglik_drop_tol,
      cg_runner_fn = cg_runner_fn
    ))
  }

  .gl_run_fit_rs_optimizer(
    optimizer_context = optimizer_context,
    mm = mm,
    margin_dist = margin_dist,
    copula_link = copula_link,
    copula_dist = copula_dist,
    dataset = dataset,
    include_dlcopdpar = include_dlcopdpar,
    check_dlcopdpar_gradient = check_dlcopdpar_gradient,
    discrete_score_method = discrete_score_method,
    verbose = verbose,
    max_outer_iter = max_outer_iter,
    check_elapsed_budget = check_elapsed_budget,
    lambda_penalty_K = lambda_penalty_K,
    use_backtracking = use_backtracking,
    backtracking_max_halves = backtracking_max_halves,
    rs_smooth_trust_radius = rs_smooth_trust_radius,
    rs_update_lambda = rs_update_lambda,
    plot_results = plot_results,
    true_val = true_val,
    max_inner_iter = max_inner_iter,
    max_negative_outer_streak = max_negative_outer_streak,
    step_adjustment = step_adjustment,
    max_steps = max_steps,
    start_step_size = start_step_size,
    rs_runner_fn = rs_runner_fn
  )
}
