#' Main entry point for model fitting, called from gamlss_longitudinal().
#' 
#' This function orchestrates the entire model fitting process, including:
#' 1. Preprocessing and validation of input data and formulas by calling workflow_fn = .gl_prepare_fit_workflow (model-fit-workflow.R),
#' 2. Execution of the optimization loop by calling optimizer_fn = .gl_run_prepared_fit_optimizer (model-fit-optimizer.R),
#' 3. Finalization of the fit by calling finalize_fn = .gl_finalize_prepared_fit (model-fit-finalize.R)
#' 
#' @noRd
.gl_run_gamlss_longitudinal_entrypoint <- function(
    dataset,
    margin_dist,
    copula_dist,
    time_var,
    subject_var,
    mu.formula,
    sigma.formula,
    nu.formula,
    tau.formula,
    theta.formula,
    zeta.formula,
    include_dlcopdpar,
    check_dlcopdpar_gradient,
    inner_stop_crit,
    outer_stop_crit,
    start_step_size,
    step_adjustment,
    max_steps,
    start_from,
    warm_start_joint,
    warm_start_joint_iter,
    verbose,
    plot_results,
    true_val,
    method,
    max_outer_iter,
    max_inner_iter,
    max_negative_outer_streak,
    max_elapsed_sec,
    use_backtracking,
    backtracking_max_halves,
    cg_max_stall,
    cg_max_delta,
    cg_armijo_c1,
    cg_grad_tol,
    cg_step_tol,
    cg_update_lambda,
    cg_lambda_update_every,
    cg_max_lambda_updates,
    cg_raw_loglik_drop_tol,
    cg_line_search,
    cg_max_line_search_evals,
    cg_gradient_method,
    discrete_score_method,
    cg_zeta_hessian,
    cg_hessian_method,
    compute_vcov,
    vcov_method,
    vcov_numderiv,
    use_Rcpp,
    lambda_start,
    lambda_penalty_K,
    rs_update_lambda,
    rs_smooth_trust_radius,
    time_fn = Sys.time,
    capability_preflight_fn = .gl_preflight_fit_capabilities,
    margin_normalizer_fn = .normalise_margin_dist_links,
    budget_checker_fn = .gl_build_elapsed_budget_checker,
    workflow_fn = .gl_prepare_fit_workflow,
    optimizer_fn = .gl_run_prepared_fit_optimizer,
    finalize_fn = .gl_finalize_prepared_fit) {
  fit_start_time <- time_fn()

  capability_preflight_fn(
    dataset = dataset,
    margin_dist = margin_dist,
    copula_dist = copula_dist,
    mu.formula = mu.formula
  )

  margin_dist <- margin_normalizer_fn(margin_dist)

  check_elapsed_budget <- budget_checker_fn(
    fit_start_time = fit_start_time,
    max_elapsed_sec = max_elapsed_sec
  )

  fit_workflow <- workflow_fn(
    dataset = dataset,
    margin_dist = margin_dist,
    copula_dist = copula_dist,
    time_var = time_var,
    subject_var = subject_var,
    mu.formula = mu.formula,
    sigma.formula = sigma.formula,
    nu.formula = nu.formula,
    tau.formula = tau.formula,
    theta.formula = theta.formula,
    zeta.formula = zeta.formula,
    include_dlcopdpar = include_dlcopdpar,
    inner_stop_crit = inner_stop_crit,
    outer_stop_crit = outer_stop_crit,
    start_step_size = start_step_size,
    step_adjustment = step_adjustment,
    max_steps = max_steps,
    start_from = start_from,
    warm_start_joint = warm_start_joint,
    warm_start_joint_iter = warm_start_joint_iter,
    verbose = verbose,
    true_val = true_val,
    method = method,
    max_inner_iter = max_inner_iter,
    max_negative_outer_streak = max_negative_outer_streak,
    max_elapsed_sec = max_elapsed_sec,
    use_backtracking = use_backtracking,
    backtracking_max_halves = backtracking_max_halves,
    cg_max_stall = cg_max_stall,
    cg_max_delta = cg_max_delta,
    cg_armijo_c1 = cg_armijo_c1,
    cg_grad_tol = cg_grad_tol,
    cg_step_tol = cg_step_tol,
    cg_update_lambda = cg_update_lambda,
    cg_lambda_update_every = cg_lambda_update_every,
    cg_max_lambda_updates = cg_max_lambda_updates,
    cg_raw_loglik_drop_tol = cg_raw_loglik_drop_tol,
    cg_line_search = cg_line_search,
    cg_max_line_search_evals = cg_max_line_search_evals,
    cg_gradient_method = cg_gradient_method,
    discrete_score_method = discrete_score_method,
    cg_zeta_hessian = cg_zeta_hessian,
    cg_hessian_method = cg_hessian_method,
    vcov_method = vcov_method,
    vcov_numderiv = vcov_numderiv,
    use_Rcpp = use_Rcpp,
    lambda_start = lambda_start,
    lambda_penalty_K = lambda_penalty_K,
    rs_smooth_trust_radius = rs_smooth_trust_radius
  )

  optimizer_state <- optimizer_fn(
    fit_workflow = fit_workflow,
    margin_dist = margin_dist,
    copula_dist = copula_dist,
    include_dlcopdpar = include_dlcopdpar,
    check_dlcopdpar_gradient = check_dlcopdpar_gradient,
    verbose = verbose,
    cg_armijo_c1 = cg_armijo_c1,
    cg_update_lambda = cg_update_lambda,
    lambda_penalty_K = lambda_penalty_K,
    rs_update_lambda = rs_update_lambda,
    plot_results = plot_results,
    true_val = true_val,
    max_outer_iter = max_outer_iter,
    max_inner_iter = max_inner_iter,
    max_negative_outer_streak = max_negative_outer_streak,
    use_backtracking = use_backtracking,
    check_elapsed_budget = check_elapsed_budget
  )

  finalize_fn(
    optimizer_state = optimizer_state,
    fit_workflow = fit_workflow,
    margin_dist = margin_dist,
    copula_dist = copula_dist,
    include_dlcopdpar = include_dlcopdpar,
    original_formulas = .gl_original_formula_bundle(
      mu.formula = mu.formula,
      sigma.formula = sigma.formula,
      nu.formula = nu.formula,
      tau.formula = tau.formula,
      theta.formula = theta.formula,
      zeta.formula = zeta.formula
    ),
    time_var = time_var,
    subject_var = subject_var,
    fit_start_time = fit_start_time,
    compute_vcov = compute_vcov,
    verbose = verbose,
    max_outer_iter = max_outer_iter
  )
}
